interface LibAInstanceClass {
    void LibAInstanceClass();
    attribute long intValue;
};

interface LibAClass {
    void LibAClass();
    long addInt(LibAInstanceClass obj1, LibAInstanceClass obj2);
};