interface ParentClass {
    float addFloatValue(float a, float b);
    boolean invertBoolean(boolean value);
};

interface NormalClass {
    void NormalClassTest();
    long addIntValue(long a, long b);
};
NormalClass implements ParentClass;