interface ParentClassTest {
    float getFloatValue();
};

interface NormalClassTest {
    long getIntValue();
    boolean getBoolValue(float floatValue);
};
NormalClassTest implements ParentClassTest;