
interface IDLString {
    void IDLString();
    void clear();
    void append([Const] DOMString text);
    void append([Const] DOMString text, long size);
    long size();
    byte at(long index);
    [Const] DOMString data();
    [Const] DOMString c_str();
};

interface IDLStringView {
    void IDLStringView([Const] DOMString text);
    void IDLStringView([Const] DOMString text, long size);
    long size();
    byte at(long index);
    [Const] DOMString data();
};

interface IDLBoolArray {
    void IDLBoolArray(long size);
    void resize(long size);
    void clear();
    boolean getValue(long index);
    void setValue(long index, boolean value);
    long getSize();
    long getPointer();
    void copy([Ref] IDLBoolArray src, long srcOffset, long destOffset, long length);
};

interface IDLIntArray {
    void IDLIntArray(long size);
    void resize(long size);
    void clear();
    long getValue(long index);
    void setValue(long index, long value);
    long getSize();
    long getPointer();
    void copy([Ref] IDLIntArray src, long srcOffset, long destOffset, long length);
};

interface IDLFloatArray {
    void IDLFloatArray(long size);
    void resize(long size);
    void clear();
    float getValue(long index);
    void setValue(long index, float value);
    long getSize();
    long getPointer();
    void copy([Ref] IDLFloatArray src, long srcOffset, long destOffset, long length);
};

interface IDLDoubleArray {
    void IDLDoubleArray(long size);
    void resize(long size);
    void clear();
    double getValue(long index);
    void setValue(long index, double value);
    long getSize();
    long getPointer();
    void copy([Ref] IDLDoubleArray src, long srcOffset, long destOffset, long length);
};

interface IDLByteArray {
    void IDLByteArray(long size);
    void resize(long size);
    void clear();
    byte getValue(long index);
    void setValue(long index, byte value);
    long getSize();
    long getPointer();
    void copy([Ref] IDLByteArray src, long srcOffset, long destOffset, long length);
};