/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib;

public class DefaultInterface extends InterfaceClass {

    static public final DefaultInterface T_01 = new DefaultInterface((byte) 1, (char) 1);

    static public final DefaultInterface T_02 = new DefaultInterface((byte) 1, (char) 1);

    static public final DefaultInterface T_03 = new DefaultInterface((byte) 1, (char) 1);

    public DefaultInterface() {
        super((byte) 1, (char) 1);
        long addr = createNATIVE();
        initNative(addr, true);
    }

    /*[-C++;-NATIVE]
return (jlong)new DefaultInterface();
*/
    private static native long createNATIVE();

    public DefaultInterface(byte b, char c) {
        super((byte) 1, (char) 1);
    }
}
