/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib;

import com.github.xpenatan.jparser.example.lib.idl.IDLEnum;

public class EnumWithinClass implements IDLEnum {

    public static final int e_val = e_val_NATIVE();

    /*[-C++;-NATIVE]
return (jlong)NormalClass::e_val;
*/
    private static native int e_val_NATIVE();
}
