/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib;

import com.github.xpenatan.jparser.example.lib.idl.IDLEnum;

public class EnumTwoLib implements IDLEnum {

    public static final int EnumTwoLib_THIRD = EnumTwoLib_THIRD_NATIVE();

    /*[-C++;-NATIVE]
return (jlong)EnumTwoLib_THIRD;
*/
    private static native int EnumTwoLib_THIRD_NATIVE();

    public static final int EnumTwoLib_FOURTH = EnumTwoLib_FOURTH_NATIVE();

    /*[-C++;-NATIVE]
return (jlong)EnumTwoLib_FOURTH;
*/
    private static native int EnumTwoLib_FOURTH_NATIVE();
}
