/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib;

import com.github.xpenatan.jparser.example.lib.idl.IDLEnum;

public class EnumClassWithinClass implements IDLEnum {

    public static final int testEnum = testEnum_NATIVE();

    /*[-C++;-NATIVE]
return (jlong)EnumClassWithinClass::testEnum;
*/
    private static native int testEnum_NATIVE();
}
