/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib;

import com.github.xpenatan.jparser.loader.JParserLibraryLoader;
import com.github.xpenatan.jparser.example.lib.idl.helper.IDLByteArray;

public class ExampleLibLoader {

    /*[-C++;-NATIVE]
        #include "CustomCode.h"
    */
    public static void init(Runnable run) {
        JParserLibraryLoader libraryLoader = new JParserLibraryLoader();
        libraryLoader.load("exampleLib");
        IDLByteArray test = new IDLByteArray(1);
        test.setValue(0, (byte) 1);
        run.run();
    }
}
