/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib;

import com.github.xpenatan.jparser.example.lib.idl.IDLBase;
import com.github.xpenatan.jparser.example.lib.subpackage.ParamData;

public class InterfaceClass extends IDLBase {

    static public final InterfaceClass T_01 = new InterfaceClass((byte) 1, (char) 1);

    static public final InterfaceClass T_02 = new InterfaceClass((byte) 1, (char) 1);

    static public final InterfaceClass T_03 = new InterfaceClass((byte) 1, (char) 1);

    public InterfaceClass(byte b, char c) {
    }

    public void onParamCall(ParamData data) {
        onParamCallNATIVE(getCPointer(), (data != null ? data.getCPointer() : 0));
    }

    /*[-C++;-NATIVE]
InterfaceClass* nativeObject = (InterfaceClass*)this_addr;
nativeObject->onParamCall(*((ParamData* )data_addr));
*/
    private static native void onParamCallNATIVE(long this_addr, long data_addr);
}
