/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib;

import com.github.xpenatan.jparser.example.lib.idl.IDLBase;

public class OperatorClass extends IDLBase {

    static public final OperatorClass T_01 = new OperatorClass((byte) 1, (char) 1);

    static public final OperatorClass T_02 = new OperatorClass((byte) 1, (char) 1);

    static public final OperatorClass T_03 = new OperatorClass((byte) 1, (char) 1);

    public OperatorClass() {
        long addr = createNATIVE();
        initNative(addr, true);
    }

    /*[-C++;-NATIVE]
return (jlong)new OperatorClass();
*/
    private static native long createNATIVE();

    public OperatorClass(byte b, char c) {
    }

    public OperatorClass copy(OperatorClass value) {
        copyNATIVE(getCPointer(), (value != null ? value.getCPointer() : 0));
        return this;
    }

    /*[-C++;-NATIVE]
OperatorClass* nativeObject = (OperatorClass*)this_addr;
return (jlong)&(*nativeObject = *((OperatorClass* )value_addr));
*/
    private static native long copyNATIVE(long this_addr, long value_addr);

    public float value() {
        return get_valueNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
OperatorClass* nativeObject = (OperatorClass*)this_addr;
return nativeObject->value;
*/
    private static native float get_valueNATIVE(long this_addr);

    public void value(float value) {
        set_valueNATIVE(getCPointer(), value);
    }

    /*[-C++;-NATIVE]
OperatorClass* nativeObject = (OperatorClass*)this_addr;
nativeObject->value = value;
*/
    private static native void set_valueNATIVE(long this_addr, float value);
}
