/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib;

import com.github.xpenatan.jparser.example.lib.idl.IDLBase;

public class ParentClass extends IDLBase {

    static public final ParentClass T_01 = new ParentClass((byte) 1, (char) 1);

    static public final ParentClass T_02 = new ParentClass((byte) 1, (char) 1);

    static public final ParentClass T_03 = new ParentClass((byte) 1, (char) 1);

    public ParentClass(byte b, char c) {
    }

    public float addFloatValue(float a, float b) {
        return addFloatValueNATIVE(getCPointer(), a, b);
    }

    /*[-C++;-NATIVE]
ParentClass* nativeObject = (ParentClass*)this_addr;
return nativeObject->addFloatValue(a, b);
*/
    private static native float addFloatValueNATIVE(long this_addr, float a, float b);

    public boolean invertBoolean(boolean value) {
        return invertBooleanNATIVE(getCPointer(), value);
    }

    /*[-C++;-NATIVE]
ParentClass* nativeObject = (ParentClass*)this_addr;
return nativeObject->invertBoolean(value);
*/
    private static native boolean invertBooleanNATIVE(long this_addr, boolean value);
}
