/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib;

import com.github.xpenatan.jparser.example.lib.idl.IDLBase;

public class ReturnClass extends IDLBase {

    static public final ReturnClass T_01 = new ReturnClass((byte) 1, (char) 1);

    static public final ReturnClass T_02 = new ReturnClass((byte) 1, (char) 1);

    static public final ReturnClass T_03 = new ReturnClass((byte) 1, (char) 1);

    public ReturnClass() {
        long addr = createNATIVE();
        initNative(addr, true);
    }

    /*[-C++;-NATIVE]
return (jlong)new ReturnClass();
*/
    private static native long createNATIVE();

    public ReturnClass(byte b, char c) {
    }

    public ReturnClass copy(ReturnClass value) {
        copyNATIVE(getCPointer(), (value != null ? value.getCPointer() : 0));
        return this;
    }

    /*[-C++;-NATIVE]
ReturnClass* nativeObject = (ReturnClass*)this_addr;
return (jlong)&(*nativeObject = *((ReturnClass* )value_addr));
*/
    private static native long copyNATIVE(long this_addr, long value_addr);

    public float value() {
        return get_valueNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
ReturnClass* nativeObject = (ReturnClass*)this_addr;
return nativeObject->value;
*/
    private static native float get_valueNATIVE(long this_addr);

    public void value(float value) {
        set_valueNATIVE(getCPointer(), value);
    }

    /*[-C++;-NATIVE]
ReturnClass* nativeObject = (ReturnClass*)this_addr;
nativeObject->value = value;
*/
    private static native void set_valueNATIVE(long this_addr, float value);
}
