[versions]
jParserGroup = "com.github.xpenatan.jParser"
jParserName = "jParser"
jParserRelease = "1.2.6"
jParserSnapshot = "-SNAPSHOT"

javaMain = "1.8"
javaWeb = "17"
javaFfm = "25"
teavm = "0.15.0"
javaparser = "3.26.1"
jMultiplatform = "0.1.3"
gdx = "1.14.2"
gdxTeavm = "1.6.0"
junit = "4.13.2"
desugarJdkLibs = "2.0.3"
easyPublishing = "-SNAPSHOT"
androidGradlePlugin = "9.1.1"

[libraries]
javaparserCore = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser" }
javaparserSymbolSolver = { module = "com.github.javaparser:javaparser-symbol-solver-core", version.ref = "javaparser" }
jMultiplatform = { module = "com.github.xpenatan:jMultiplatform", version.ref = "jMultiplatform" }
junit = { module = "junit:junit", version.ref = "junit" }
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }

teavmTooling = { module = "org.teavm:teavm-tooling", version.ref = "teavm" }
teavmCore = { module = "org.teavm:teavm-core", version.ref = "teavm" }
teavmClasslib = { module = "org.teavm:teavm-classlib", version.ref = "teavm" }
teavmExtensionSpi = { module = "org.teavm:teavm-extension-spi", version.ref = "teavm" }
teavmInterop = { module = "org.teavm:teavm-interop", version.ref = "teavm" }
teavmJso = { module = "org.teavm:teavm-jso", version.ref = "teavm" }
teavmJsoApis = { module = "org.teavm:teavm-jso-apis", version.ref = "teavm" }
teavmJsoImpl = { module = "org.teavm:teavm-jso-impl", version.ref = "teavm" }

gdxCore = { module = "com.badlogicgames.gdx:gdx", version.ref = "gdx" }
gdxBackendAndroid = { module = "com.badlogicgames.gdx:gdx-backend-android", version.ref = "gdx" }
gdxBackendLwjgl3 = { module = "com.badlogicgames.gdx:gdx-backend-lwjgl3", version.ref = "gdx" }
gdxPlatform = { module = "com.badlogicgames.gdx:gdx-platform", version.ref = "gdx" }
gdxTeavmBackendWeb = { module = "com.github.xpenatan.gdx-teavm:backend-web", version.ref = "gdxTeavm" }

[bundles]
teavmCompiler = ["teavmTooling", "teavmClasslib"]
teavmC = ["teavmCore", "teavmClasslib", "teavmExtensionSpi"]
teavmWeb = ["teavmClasslib", "teavmJso", "teavmJsoApis", "teavmJsoImpl", "teavmExtensionSpi"]

[plugins]
easyPublishing = { id = "com.github.xpenatan.easy-publishing", version.ref = "easyPublishing" }
jParser = { id = "com.github.xpenatan.jparser", version.ref = "jParserSnapshot" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
