if(NOT DEFINED JPARSER_TEAVMC_APP_TARGET OR "${JPARSER_TEAVMC_APP_TARGET}" STREQUAL "")
  if(DEFINED TEAVM_APP_TARGET AND NOT "${TEAVM_APP_TARGET}" STREQUAL "")
    set(JPARSER_TEAVMC_APP_TARGET "${TEAVM_APP_TARGET}")
  else()
    message(FATAL_ERROR "Set JPARSER_TEAVMC_APP_TARGET before including the jParser TeaVM C loader hook.")
  endif()
endif()

get_filename_component(JPARSER_TEAVMC_LOADER_EXTERNAL_CPP_ROOT
  "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(JPARSER_TEAVMC_LOADER_ROOT
  "${JPARSER_TEAVMC_LOADER_EXTERNAL_CPP_ROOT}/jparser/loader")
set(JPARSER_TEAVMC_LOADER_SOURCE
  "${JPARSER_TEAVMC_LOADER_ROOT}/teavmc_loader.cpp")
set(JPARSER_TEAVMC_LOADER_HEADER
  "${JPARSER_TEAVMC_LOADER_ROOT}/teavmc_loader.h")

if(NOT EXISTS "${JPARSER_TEAVMC_LOADER_SOURCE}")
  message(FATAL_ERROR "Missing jParser TeaVM C loader source: ${JPARSER_TEAVMC_LOADER_SOURCE}")
endif()
if(NOT EXISTS "${JPARSER_TEAVMC_LOADER_HEADER}")
  message(FATAL_ERROR "Missing jParser TeaVM C loader header: ${JPARSER_TEAVMC_LOADER_HEADER}")
endif()

if(NOT DEFINED JPARSER_TEAVMC_GENERATED_SOURCE_ROOT
    OR "${JPARSER_TEAVMC_GENERATED_SOURCE_ROOT}" STREQUAL "")
  set(JPARSER_TEAVMC_GENERATED_SOURCE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/c/src")
endif()

file(GLOB_RECURSE JPARSER_TEAVMC_LOADER_GENERATED_C_SOURCES CONFIGURE_DEPENDS
  "${JPARSER_TEAVMC_GENERATED_SOURCE_ROOT}/*.c")
if(MSVC)
  foreach(JPARSER_TEAVMC_LOADER_GENERATED_C_SOURCE
      IN LISTS JPARSER_TEAVMC_LOADER_GENERATED_C_SOURCES)
    set_property(SOURCE "${JPARSER_TEAVMC_LOADER_GENERATED_C_SOURCE}" APPEND
      PROPERTY COMPILE_OPTIONS "/FI${JPARSER_TEAVMC_LOADER_HEADER}")
  endforeach()
else()
  foreach(JPARSER_TEAVMC_LOADER_GENERATED_C_SOURCE
      IN LISTS JPARSER_TEAVMC_LOADER_GENERATED_C_SOURCES)
    set_property(SOURCE "${JPARSER_TEAVMC_LOADER_GENERATED_C_SOURCE}" APPEND
      PROPERTY COMPILE_OPTIONS "-include" "${JPARSER_TEAVMC_LOADER_HEADER}")
  endforeach()
endif()

get_property(JPARSER_TEAVMC_LOADER_ADDED TARGET ${JPARSER_TEAVMC_APP_TARGET}
  PROPERTY JPARSER_TEAVMC_LOADER_ADDED)
if(NOT JPARSER_TEAVMC_LOADER_ADDED)
  enable_language(CXX)
  target_sources(${JPARSER_TEAVMC_APP_TARGET} PRIVATE
    "${JPARSER_TEAVMC_LOADER_SOURCE}")
  set_source_files_properties("${JPARSER_TEAVMC_LOADER_SOURCE}" PROPERTIES LANGUAGE CXX)
  target_include_directories(${JPARSER_TEAVMC_APP_TARGET} PRIVATE
    "${JPARSER_TEAVMC_LOADER_ROOT}")
  target_compile_features(${JPARSER_TEAVMC_APP_TARGET} PRIVATE cxx_std_17)
  if(CMAKE_DL_LIBS)
    target_link_libraries(${JPARSER_TEAVMC_APP_TARGET} PRIVATE ${CMAKE_DL_LIBS})
  endif()
  set_property(TARGET ${JPARSER_TEAVMC_APP_TARGET}
    PROPERTY JPARSER_TEAVMC_LOADER_ADDED TRUE)
endif()
