/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib.idl;

/**
 * @author xpenatan
 */
public interface IDLEnum {
}
