/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib.idl.helper;

import com.github.xpenatan.jparser.example.lib.idl.IDLBase;

public class IDLByteArray extends IDLBase {

    public IDLByteArray(int size) {
        long addr = createNATIVE(size);
        initNative(addr, true);
    }

    public void copy(byte[] array) {
        int length = array.length;
        resize(length);
        for (int i = 0; i < length; i++) {
            byte value = array[i];
            setValue(i, value);
        }
    }

    public static void arraycopy(byte[] src, int srcPos, IDLByteArray dest, int destPos, int length) {
        int srcP = srcPos;
        int destP = destPos;
        int count = 0;
        while (count < length) {
            byte srcByte = src[srcP];
            srcP++;
            dest.setValue(destP, srcByte);
            destP++;
            count++;
        }
    }

    public static void arraycopy(IDLByteArray src, int srcPos, byte[] dest, int destPos, int length) {
        int srcP = srcPos;
        int destP = destPos;
        int count = 0;
        while (count < length) {
            byte srcByte = src.getValue(srcP);
            srcP++;
            dest[destP] = srcByte;
            destP++;
            count++;
        }
    }

    /*[-C++;-NATIVE]
return (jlong)new IDLByteArray(size);
*/
    private static native long createNATIVE(int size);

    public IDLByteArray(byte b, char c) {
    }

    public void resize(int size) {
        resizeNATIVE(getCPointer(), size);
    }

    /*[-C++;-NATIVE]
IDLByteArray* nativeObject = (IDLByteArray*)this_addr;
nativeObject->resize(size);
*/
    private static native void resizeNATIVE(long this_addr, int size);

    public byte getValue(int index) {
        return getValueNATIVE(getCPointer(), index);
    }

    /*[-C++;-NATIVE]
IDLByteArray* nativeObject = (IDLByteArray*)this_addr;
return nativeObject->getValue(index);
*/
    private static native byte getValueNATIVE(long this_addr, int index);

    public void setValue(int index, byte value) {
        setValueNATIVE(getCPointer(), index, value);
    }

    /*[-C++;-NATIVE]
IDLByteArray* nativeObject = (IDLByteArray*)this_addr;
nativeObject->setValue(index, value);
*/
    private static native void setValueNATIVE(long this_addr, int index, byte value);

    public long getPointer() {
        return getPointerNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
IDLByteArray* nativeObject = (IDLByteArray*)this_addr;
return nativeObject->getPointer();
*/
    private static native long getPointerNATIVE(long this_addr);

    public int getSize() {
        return getSizeNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
IDLByteArray* nativeObject = (IDLByteArray*)this_addr;
return nativeObject->getSize();
*/
    private static native int getSizeNATIVE(long this_addr);
}
