/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib.idl.helper;

import com.github.xpenatan.jparser.example.lib.idl.IDLBase;

public class IDLDoubleArray extends IDLBase {

    public IDLDoubleArray(int size) {
        long addr = createNATIVE(size);
        initNative(addr, true);
    }

    public void copy(double[] array) {
        int length = array.length;
        resize(length);
        for (int i = 0; i < length; i++) {
            double value = array[i];
            setValue(i, value);
        }
    }

    /*[-C++;-NATIVE]
return (jlong)new IDLDoubleArray(size);
*/
    private static native long createNATIVE(int size);

    public IDLDoubleArray(byte b, char c) {
    }

    public void resize(int size) {
        resizeNATIVE(getCPointer(), size);
    }

    /*[-C++;-NATIVE]
IDLDoubleArray* nativeObject = (IDLDoubleArray*)this_addr;
nativeObject->resize(size);
*/
    private static native void resizeNATIVE(long this_addr, int size);

    public double getValue(int index) {
        return getValueNATIVE(getCPointer(), index);
    }

    /*[-C++;-NATIVE]
IDLDoubleArray* nativeObject = (IDLDoubleArray*)this_addr;
return nativeObject->getValue(index);
*/
    private static native double getValueNATIVE(long this_addr, int index);

    public void setValue(int index, double value) {
        setValueNATIVE(getCPointer(), index, value);
    }

    /*[-C++;-NATIVE]
IDLDoubleArray* nativeObject = (IDLDoubleArray*)this_addr;
nativeObject->setValue(index, value);
*/
    private static native void setValueNATIVE(long this_addr, int index, double value);

    public long getPointer() {
        return getPointerNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
IDLDoubleArray* nativeObject = (IDLDoubleArray*)this_addr;
return nativeObject->getPointer();
*/
    private static native long getPointerNATIVE(long this_addr);

    public int getSize() {
        return getSizeNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
IDLDoubleArray* nativeObject = (IDLDoubleArray*)this_addr;
return nativeObject->getSize();
*/
    private static native int getSizeNATIVE(long this_addr);
}
