/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib.idl.helper;

import com.github.xpenatan.jparser.example.lib.idl.IDLBase;

public class IDLString extends IDLBase {

    public static IDLString TMP_EMPTY_1 = new IDLString((byte) 0, '0');

    public static IDLString TMP_1 = new IDLString();

    public static IDLString TMP_2 = new IDLString();

    public static void disposeTEMP() {
        TMP_1.dispose();
        TMP_2.dispose();
    }

    public IDLString() {
        long addr = createNATIVE();
        initNative(addr, true);
    }

    public IDLString(byte b, char c) {
    }

    public String c_str() {
        String text = c_strNATIVE(getCPointer());
        return text;
    }

    /*[-C++;-NATIVE]
        IDLString* nativeObject = (IDLString*)this_addr;
        const char* str = nativeObject->c_str();
        jstring jstrBuf = env->NewStringUTF(str);
        return jstrBuf;
    */
    private static native String c_strNATIVE(long this_addr);

    /*[-C++;-NATIVE]
return (jlong)new IDLString();
*/
    private static native long createNATIVE();

    public void clear() {
        clearNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
IDLString* nativeObject = (IDLString*)this_addr;
nativeObject->clear();
*/
    private static native void clearNATIVE(long this_addr);

    public void append(String text) {
        appendNATIVE(getCPointer(), text);
    }

    /*[-C++;-NATIVE]
IDLString* nativeObject = (IDLString*)this_addr;
nativeObject->append(text);
*/
    private static native void appendNATIVE(long this_addr, String text);

    public void append(String text, int size) {
        appendNATIVE(getCPointer(), text, size);
    }

    /*[-C++;-NATIVE]
IDLString* nativeObject = (IDLString*)this_addr;
nativeObject->append(text, size);
*/
    private static native void appendNATIVE(long this_addr, String text, int size);

    public int size() {
        return sizeNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
IDLString* nativeObject = (IDLString*)this_addr;
return nativeObject->size();
*/
    private static native int sizeNATIVE(long this_addr);

    public byte at(int index) {
        return atNATIVE(getCPointer(), index);
    }

    /*[-C++;-NATIVE]
IDLString* nativeObject = (IDLString*)this_addr;
return nativeObject->at(index);
*/
    private static native byte atNATIVE(long this_addr, int index);
}
