/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.jparser.example.lib.subpackage;

import com.github.xpenatan.jparser.example.lib.idl.IDLBase;

public class ParamData extends IDLBase {

    static public final ParamData T_01 = new ParamData((byte) 1, (char) 1);

    static public final ParamData T_02 = new ParamData((byte) 1, (char) 1);

    static public final ParamData T_03 = new ParamData((byte) 1, (char) 1);

    public ParamData() {
        long addr = createNATIVE();
        initNative(addr, true);
    }

    /*[-C++;-NATIVE]
return (jlong)new ParamData();
*/
    private static native long createNATIVE();

    public ParamData(byte b, char c) {
    }

    public int intData() {
        return get_intDataNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
ParamData* nativeObject = (ParamData*)this_addr;
return nativeObject->intData;
*/
    private static native int get_intDataNATIVE(long this_addr);

    public void intData(int intData) {
        set_intDataNATIVE(getCPointer(), intData);
    }

    /*[-C++;-NATIVE]
ParamData* nativeObject = (ParamData*)this_addr;
nativeObject->intData = intData;
*/
    private static native void set_intDataNATIVE(long this_addr, int intData);

    public float floatData() {
        return get_floatDataNATIVE(getCPointer());
    }

    /*[-C++;-NATIVE]
ParamData* nativeObject = (ParamData*)this_addr;
return nativeObject->floatData;
*/
    private static native float get_floatDataNATIVE(long this_addr);

    public void floatData(float floatData) {
        set_floatDataNATIVE(getCPointer(), floatData);
    }

    /*[-C++;-NATIVE]
ParamData* nativeObject = (ParamData*)this_addr;
nativeObject->floatData = floatData;
*/
    private static native void set_floatDataNATIVE(long this_addr, float floatData);
}
