name: Dispatch Build

on:
  workflow_dispatch:
    inputs:
      isRelease:
        required: true
        type: boolean
      shouldUpload:
        required: true
        type: boolean
jobs:
  build-and-upload:
    uses: ./.github/workflows/build_and_upload.yml
    with:
      isRelease: ${{ inputs.isRelease }}
      shouldUpload: ${{ inputs.shouldUpload }}
    secrets: inherit
