name: Deploy Libs

on:
  push:
    branches:
      - master

jobs:
  build_Linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Check Ant
        run: ant -version

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build classes
        run: ./gradlew build

      - name: Upload to repository
        run: ./gradlew publish
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SIGNING_KEY: ${{ secrets.PGP_SECRET }}
          SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}