name: Deploy Libs

on:
  push:
    branches:
      - master

jobs:
  build_Linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Ant
        run: ant -version
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build classes
        run: ./gradlew build
      - name: Upload to repository
        run: ./gradlew publish
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}