name: Deploy Libs

on:
  push:
    branches:
      - master

jobs:
  build_Linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Ant
        run: ant -version
      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Turn off the gradle Daemon
        shell: bash
        run: ./gradle --stop
      - name: Cleanup the Gradle cache
        shell: bash
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Build classes
        run: ./gradlew build
      - name: Upload to repository
        run: ./gradlew publish
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          signingKey: ${{ secrets.PGP_SECRET }}
          signingPassword: ${{ secrets.PGP_PASSPHRASE }}